server:
  port: 4000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for /api/patients/** to patient-service
        - id: patient_service_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/patients/**
          filters:
            - SetPath=/patients

        # Route for /api-docs/patients to patient-service /v3/api-docs
        - id: api_docs_patient_route
          uri: http://localhost:8081
          predicates:
            - Path=/api-docs/patients
          filters:
            - SetPath=/v3/api-docs