### POST request to login user
POST http://localhost:8084/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "password123"
}

> {% client.global.set("authToken", response.body.data.token) %}

###